services:
  postgres:
    container_name: diploma-postgres
    image: postgres:14.2
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - diploma_project_network
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  cache:
    container_name: diploma-redis
    image: redis:7.0
    restart: always
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    env_file:
      - ${DJANGO_PROJECT_NAME}/.env
    command: redis-server --save 20 1 --loglevel warning --port ${REDIS_PORT}
    volumes:
      - cache:/data
    networks:
      - diploma_project_network
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  wsgi:
    restart: unless-stopped
    container_name: diploma-wsgi
    build: .
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - ./${DJANGO_PROJECT_NAME}:/app
    env_file:
      - ${DJANGO_PROJECT_NAME}/.env
    environment:
      - CONTAINER_TYPE=master
    depends_on:
      - postgres
      - cache
    networks:
      - diploma_project_network
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  asgi:
    restart: unless-stopped
    container_name: diploma-asgi
    build: .
    expose:
      - 8001
    ports:
      - "8001:8001"
    volumes:
      - ./${DJANGO_PROJECT_NAME}:/app
    env_file:
      - ${DJANGO_PROJECT_NAME}/.env
    environment:
      - CONTAINER_TYPE=asgi
    depends_on:
      - postgres
      - cache
    networks:
      - diploma_project_network
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  celery:
    build: .
    volumes:
      - ./${DJANGO_PROJECT_NAME}:/app
    env_file:
      - ${DJANGO_PROJECT_NAME}/.env
    environment:
      - CONTAINER_TYPE=worker
      - CELERY_BROKER=redis://:${REDIS_PASSWORD}@cache:${REDIS_PORT}/1
      - CELERY_BACKEND=redis://:${REDIS_PASSWORD}@cache:${REDIS_PORT}/1
    restart: unless-stopped
    depends_on:
      - wsgi
      - cache
      - postgres
    networks:
      - diploma_project_network
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "5"

  celery_beat:
    build: .
    volumes:
      - ./${DJANGO_PROJECT_NAME}:/app
    env_file:
      - ${DJANGO_PROJECT_NAME}/.env
    environment:
      - CONTAINER_TYPE=beat
      - CELERY_BROKER=redis://:${REDIS_PASSWORD}@cache:${REDIS_PORT}/1
      - CELERY_BACKEND=redis://:${REDIS_PASSWORD}@cache:${REDIS_PORT}/1
    restart: unless-stopped
    depends_on:
      - wsgi
      - cache
      - postgres
    networks:
      - diploma_project_network

volumes:
  pgdata:
    driver: local
  cache:
    driver: local

networks:
  diploma_project_network:
