# Generated by Django 5.0.4 on 2024-04-18 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='subscribers',
            new_name='friends',
        ),
    ]
