# Generated by Django 5.0.4 on 2024-04-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('profiles', '0004_alter_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='post_topics', to='posts.topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='topic_likes', to='profiles.profile'),
        ),
    ]
